# 测试 bus 总线的时候有两个 order-service 请求这个配置文件，所以不能在这里配置port
# server:
#   port: 9091

spring:
  application:
    name: order-service  # 应用名称


# 配置 Eureka 注册中心
eureka:
  instance:
    prefer-ip-address: true           #是否使用 ip 注册地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  # ip:port
  client:
    service-url:                 # 设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

# 自定义名称
name: order-service-prod
password: '{cipher}AQAJdimpr7vYMazXLjR4xmhVTFQE+mDqUWjksnoWqUYkAPwb3wOklh3ckHpIySWeRqCJnMb4FOGxDzuIu6Vhk2ZZ3997xACSkF6MVKUZcO3On+HHC8z9BGJocLwTjvRl3bdE+CCP+hFArafk1zcQCMOPU6nj08ezudRYtRstFY/6XtZDgxD1k3dBdRpr6ZSpZv5jyrn8LnnKjg6XRpXB4ACZF0JeTH6T42E/gcil8aNrKaXaHjsPzkqvkYOa6VzlkHZ1JNEKomWaMfkq12Z0WYjlSf8gydaYV2fMAmQkbqaF4FCtQWwIQ/dXivDSWY+lgg30Tv+FHae0OyjRIA8MdZHx8T3aMpEiI6BQri8o4XmEI+ax0oEuEmE1MtW1W2e4Gtc='
